"""Adiciona tabela Sala e FK em Agendamento

Revision ID: 2ffa412eea8c
Revises: cf005a36e1bf
Create Date: 2025-04-25 15:01:52.111359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffa412eea8c'
down_revision = 'cf005a36e1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sala_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sala', ['sala_id'], ['id'])
        batch_op.drop_column('sala')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sala', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sala_id')

    op.drop_table('sala')
    # ### end Alembic commands ###
