"""Add payment fields to Agendamento

Revision ID: 5f32e59f4bf1
Revises: 894e5552c8cc
Create Date: 2025-04-19 14:51:08.327178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f32e59f4bf1'
down_revision = '894e5552c8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pagamento_entrada', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_pagamento_final', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('metodo_pagamento', sa.String(length=20), nullable=True))
        batch_op.drop_column('data_pagamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pagamento', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('metodo_pagamento')
        batch_op.drop_column('data_pagamento_final')
        batch_op.drop_column('data_pagamento_entrada')

    # ### end Alembic commands ###
