"""criando tabelas

Revision ID: 894e5552c8cc
Revises: 
Create Date: 2025-04-10 10:34:53.791662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894e5552c8cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.alter_column('valor_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('entrada',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('saldo',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
        batch_op.alter_column('servico',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('servico',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.alter_column('saldo',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('entrada',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('valor_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
