"""Adiciona colunas de método e data de pagamento

Revision ID: cf005a36e1bf
Revises: 5f32e59f4bf1
Create Date: 2025-04-23 13:23:41.280494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf005a36e1bf'
down_revision = '5f32e59f4bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pagamento_entrada', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('metodo_pagamento_final', sa.String(length=20), nullable=True))
        batch_op.drop_column('metodo_pagamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pagamento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('metodo_pagamento_final')
        batch_op.drop_column('metodo_pagamento_entrada')

    # ### end Alembic commands ###
